/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ghada
 */
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
public class Play extends javax.swing.JPanel implements MouseListener{

    /**
     * Creates new form Play
     */
    public Play() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        easyBtn = new javax.swing.JButton();
        intermediateBtn = new javax.swing.JButton();
        expertBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(203, 227, 190));

        easyBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 14)); // NOI18N
        easyBtn.setText("Easy");
        easyBtn.setMargin(new java.awt.Insets(6, 2, 2, 2));
        easyBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        easyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                easyBtnMouseClicked(evt);
            }
        });
        easyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyBtnActionPerformed(evt);
            }
        });

        intermediateBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 14)); // NOI18N
        intermediateBtn.setText("Intermediate");
        intermediateBtn.setMargin(new java.awt.Insets(6, 2, 2, 2));
        intermediateBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        intermediateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                intermediateBtnMouseClicked(evt);
            }
        });
        intermediateBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                intermediateBtnKeyPressed(evt);
            }
        });

        expertBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 14)); // NOI18N
        expertBtn.setText("Expert");
        expertBtn.setMargin(new java.awt.Insets(6, 2, 2, 2));
        expertBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expertBtnMouseClicked(evt);
            }
        });
        expertBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                expertBtnKeyPressed(evt);
            }
        });

        backBtn.setFont(new java.awt.Font("Shree Devanagari 714", 1, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.setMargin(new java.awt.Insets(6, 2, 2, 2));
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(intermediateBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(easyBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(expertBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(backBtn)
                .addGap(67, 67, 67)
                .addComponent(easyBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(intermediateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expertBtn)
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void easyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_easyBtnActionPerformed

    private void easyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyBtnMouseClicked
        GamePanel.cells=35;
        Sudoku.gamePanel();
    }//GEN-LAST:event_easyBtnMouseClicked

    private void intermediateBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_intermediateBtnKeyPressed
      
    }//GEN-LAST:event_intermediateBtnKeyPressed

    private void expertBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expertBtnKeyPressed
      
    }//GEN-LAST:event_expertBtnKeyPressed

    private void intermediateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_intermediateBtnMouseClicked
          GamePanel.cells=45;
        Sudoku.gamePanel();
    }//GEN-LAST:event_intermediateBtnMouseClicked

    private void expertBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expertBtnMouseClicked
        GamePanel.cells=55;
        Sudoku.gamePanel();
    }//GEN-LAST:event_expertBtnMouseClicked

    private void backBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseClicked
        // TODO add your handling code here:
        Sudoku.mainPanel();
    }//GEN-LAST:event_backBtnMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton easyBtn;
    private javax.swing.JButton expertBtn;
    private javax.swing.JButton intermediateBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        java.awt.Toolkit.getDefaultToolkit().beep();
    }

    @Override
    public void mousePressed(MouseEvent e) {
 java.awt.Toolkit.getDefaultToolkit().beep();    }

    @Override
    public void mouseReleased(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void mouseExited(MouseEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


}
